name: Newman run

on: 
  push:
    branches:
      - main

jobs: 
  newman:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3

      - name: Creat dir fir report 
        run: |
          mkdir testArtifacts

      - name: Istall Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Test
        run: newman run ServeRest.postman_collection.json -e ServeRest_env.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Report
          path: newman
